# -*- coding: utf-8 -*-
"""Varithon_Model_PersonReID.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBt7GdKX5oiXSoJYc9ubLys9AU4SjudD

# VariSetu — Person Re-Identification Model
### Component: Missing-Person Appearance Matching (replaces face-only search)
**Project:** VariSetu — AI Coordination Layer for Pilgrimage Safety (Varithon 2026, Team V26-GF-101)
**This notebook covers ONE of three ML models in the VariSetu system.**

---

## 1. Project Overview

VariSetu's "Voice Lost & Found" flow converts a caller's spoken description (in Marathi) of a missing
pilgrim into a search over live/recent CCTV footage. Looking at the sample transcripts in the Stage-1
report (e.g. *"White Kurta-Dhoti, Gandhi topi, carrying Tulsi mala"*), the information that is actually
usable for matching is **whole-body appearance** — clothing colour/type, build, accessories — not facial
geometry. In a dense, distant, poorly-lit crowd (the exact conditions at Wakhri Phata / Pandharpur Chowk),
face recognition is known to degrade sharply; the report itself flags this as a risk ("Face search on
crowded footage will misfire").

**Design decision (change from the original report):** the primary matching engine for this component is
built as a **person re-identification (Re-ID) model** — matching a person across non-overlapping cameras by
whole-body appearance embedding — with pretrained face recognition (ArcFace/InsightFace) kept only as an
optional secondary confirmation signal when a clear frontal face is available. This decision, and the
reasoning behind it, is documented in `MODEL_README.md` / `FRONTEND_CHANGES_REQUIRED.md` at the project level.

## 2. Problem Definition

- **Input:** a cropped person image from a CCTV frame (from any camera in the network).
- **Output:** an embedding vector such that the same real person, seen from different cameras/angles/times,
  produces embeddings that are close together (by cosine/Euclidean distance), and different people produce
  embeddings that are far apart.
- **Downstream use:** given a "last seen" crop of the missing pilgrim (or the closest available appearance
  description matched to a crop), rank all recent person-crops from the camera network by embedding distance
  and surface the top candidates to a control-room officer for confirmation (never auto-dispatch — this
  matches the report's stated mitigation).

## 3. Dataset

**Market-1501** (`pengcw1/market-1501` on Kaggle) — the standard academic benchmark for person re-ID.
- 1,501 identities captured by 6 non-overlapping outdoor cameras on a university campus.
- ~32,668 bounding-box images total, split into a fixed `train` (751 IDs), `query` (750 IDs) and
  `gallery`/`test` (750 IDs, same IDs as query, disjoint images) protocol.
- **Domain-gap limitation (stated up front, not discovered later):** Market-1501 is pedestrians on a
  campus, not pilgrims in a religious procession — different clothing distributions, crowd density, and
  camera angles than the real Wari corridor. This dataset is used because **no public pilgrimage-specific
  Re-ID dataset with individual-level labels exists** (see the dataset-search conversation earlier in this
  project). Market-1501 gives us a working, evaluable Re-ID pipeline and transferable visual features
  (edges, colour blocks, silhouette) — but real deployment would need fine-tuning on Wari-specific footage
  before going live, and that limitation is repeated in `MODEL_README.md`.

## 4. A note on the requested metrics

You asked for accuracy, recall, F1 (macro) and ROC-AUC — these are **classification/verification metrics**,
but standard person Re-ID is fundamentally a **retrieval** problem, evaluated with **CMC (Rank-1/5/10)** and
**mAP**, not classification accuracy. Reporting only classification accuracy on Re-ID would be reporting a
number that looks good but doesn't measure what the system actually needs to do (rank the correct match
near the top across cameras it has never matched that identity in before).

So this notebook computes **both**, honestly, on the parts of the pipeline where each is actually valid:

| Metric | Where it's valid here | Computed on |
|---|---|---|
| Accuracy, Precision, Recall, F1 (macro) | The auxiliary ID-classification head during training (closed-set, seen identities) | Train / held-out train-split images |
| **CMC (Rank-1/5/10), mAP** | The actual deployment task: retrieving the right person across cameras | Query vs. Gallery (standard Market-1501 protocol) |
| **ROC-AUC** | Reframed as pairwise **verification** ("is this the same person, yes/no") — the one place ROC-AUC is meaningful for Re-ID | Sampled positive/negative pairs from Query+Gallery embeddings |

This is not a workaround to avoid your request — it's how to get accuracy/recall/F1/ROC-AUC numbers that are
actually trustworthy for this task, instead of inflated numbers from the wrong evaluation protocol.

## 5. Architecture summary

`ResNet-50 (ImageNet-pretrained) → Global Average Pool → BNNeck (BatchNorm, no bias) → FC classifier`,
trained with a combined **Cross-Entropy (label smoothing) + Batch-Hard Triplet loss** — the well-established
"Bag of Tricks" strong Re-ID baseline (Luo et al., 2019). Simpler than building custom architectures, widely
reproducible, and fast enough for a hackathon-timeline Colab run (GPU recommended, not required for
inference).

## 6. Pipeline

```
Kaggle download → Validate file structure → Parse Market-1501 filenames → EDA
   → Preprocessing (resize/normalize) → Augmentation (flip, pad-crop, color jitter, random erasing)
   → Train/held-out split (classification monitoring only)
   → Model (ResNet50 + BNNeck) → Combined loss (CE + Triplet)
   → Training loop (per-epoch Accuracy/Precision/Recall/F1-macro)
   → Full Re-ID evaluation (CMC, mAP) on Query/Gallery
   → Verification evaluation (ROC-AUC) on sampled pairs
   → Visualizations (curves, CMC curve, ROC curve, t-SNE, retrieval examples, confusion matrix on subset)
   → Export artifacts → Reload → Independent inference test
```

**Note on execution:** This notebook is written to run end-to-end in Google Colab (GPU runtime recommended:
`Runtime → Change runtime type → T4 GPU`). It has not been executed in this authoring environment (no GPU,
no Kaggle network access here) — run it top-to-bottom in Colab and treat the printed metrics as the real,
first-run results. No numbers in this notebook are pre-filled or fabricated.

## 7. Setup — Install Dependencies
"""

# Core deps. torch/torchvision come pre-installed on Colab GPU runtimes;
# this pins nothing exotic so it installs cleanly on a fresh Colab runtime.
!pip install -q kagglehub scikit-learn matplotlib seaborn pandas numpy pillow tqdm umap-learn
print("Done.")

import os, glob, re, json, random, math, shutil, time
from collections import defaultdict, Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, Sampler
import torchvision
from torchvision import transforms as T
from torchvision.models import resnet50, ResNet50_Weights

from sklearn.metrics import (accuracy_score, precision_recall_fscore_support,
                              roc_curve, auc, confusion_matrix, ConfusionMatrixDisplay)

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", DEVICE)
if DEVICE.type == "cpu":
    print("WARNING: no GPU detected. Training will be slow — enable a GPU runtime in Colab "
          "(Runtime > Change runtime type > GPU) before running the training cells.")

"""## 8. Dataset Download"""

import kagglehub

# Download latest version of Market-1501 (as provided)
path = kagglehub.dataset_download("pengcw1/market-1501")
print("Path to dataset files:", path)

# The Kaggle mirror can nest the actual Market-1501 folder at varying depths
# depending on how it was zipped. Walk the tree and locate the real image
# directories by their known names rather than hard-coding a path.
def find_market1501_root(base_path):
    targets = {"bounding_box_train", "bounding_box_test", "query"}
    for root, dirs, files in os.walk(base_path):
        found = targets.intersection(set(dirs))
        if len(found) >= 2:   # train + at least one of test/query alongside it
            return root
    raise FileNotFoundError(
        "Could not locate Market-1501 folder structure under: " + base_path +
        ". Inspect the downloaded path manually with os.walk() and update this cell."
    )

DATA_ROOT = find_market1501_root(path)
print("Resolved Market-1501 root:", DATA_ROOT)
print("Contents:", os.listdir(DATA_ROOT))

TRAIN_DIR = os.path.join(DATA_ROOT, "bounding_box_train")
GALLERY_DIR = os.path.join(DATA_ROOT, "bounding_box_test")
QUERY_DIR = os.path.join(DATA_ROOT, "query")

for d in [TRAIN_DIR, GALLERY_DIR, QUERY_DIR]:
    assert os.path.isdir(d), f"Missing expected folder: {d}"
print("All three required folders found: train / gallery(test) / query.")

"""## 9. Data Validation & Filename Parsing

Market-1501 encodes identity, camera, and sequence info directly in the filename, e.g.
`0002_c1s1_000451_03.jpg`:
- `0002` — person ID (`0000` = junk/distractor, `-1` = "unlabelled" in gallery — must be excluded from Re-ID
  evaluation per the standard protocol)
- `c1` — camera ID (1–6)
- `s1` — sequence
- `000451_03` — frame/box index

We parse this explicitly and validate assumptions before trusting anything downstream — this is where
"data leakage" for Re-ID would actually happen: if we don't respect camera IDs, evaluation would count a
trivial same-camera, same-frame match as a "correct retrieval," which is not the deployment scenario.
"""

FNAME_RE = re.compile(r"^(-?\d+)_c(\d)s(\d)_(\d+)_(\d+)\.jpg$")

def parse_market1501_dir(dir_path):
    rows = []
    files = sorted(glob.glob(os.path.join(dir_path, "*.jpg")))
    bad = 0
    for f in files:
        base = os.path.basename(f)
        m = FNAME_RE.match(base)
        if not m:
            bad += 1
            continue
        pid, cam, seq, frame, box = m.groups()
        rows.append({
            "path": f, "filename": base,
            "person_id": int(pid), "camera_id": int(cam),
            "sequence": int(seq), "frame": frame, "box": int(box)
        })
    if bad:
        print(f"  [{os.path.basename(dir_path)}] {bad} filenames did not match the expected pattern (skipped).")
    return pd.DataFrame(rows)

df_train = parse_market1501_dir(TRAIN_DIR)
df_gallery = parse_market1501_dir(GALLERY_DIR)
df_query = parse_market1501_dir(QUERY_DIR)

print("Train images:      ", len(df_train), "| unique IDs:", df_train.person_id.nunique())
print("Gallery(test) images:", len(df_gallery), "| unique IDs:", df_gallery.person_id.nunique())
print("Query images:       ", len(df_query), "| unique IDs:", df_query.person_id.nunique())

# --- Duplicates check ---
for name, df in [("train", df_train), ("gallery", df_gallery), ("query", df_query)]:
    dup = df.duplicated(subset=["filename"]).sum()
    print(f"{name}: {dup} duplicate filenames")

# --- Junk / distractor IDs (standard Market-1501 convention) ---
# 0000 = junk detections (background/false detections), -1 = distractor / unlabelled in gallery.
# These MUST be excluded from identity-classification training and from being counted as
# correct/incorrect retrieval matches -- including them would corrupt both training and evaluation.
print("\nTrain person_id == 0 (junk) count:", (df_train.person_id == 0).sum())
print("Gallery person_id == -1 (distractor) count:", (df_gallery.person_id == -1).sum())
print("Gallery person_id == 0 (junk) count:", (df_gallery.person_id == 0).sum())

# --- Train/Query/Gallery identity overlap check (this IS the leakage check for Re-ID) ---
train_ids = set(df_train.person_id) - {0, -1}
query_ids = set(df_query.person_id) - {0, -1}
gallery_ids = set(df_gallery.person_id) - {0, -1}
print("\nTrain identities overlap Query identities:", len(train_ids & query_ids),
      "(should be 0 -- train and test identities must be disjoint for a valid open-set Re-ID evaluation)")
print("Query identities are subset of Gallery identities:", query_ids.issubset(gallery_ids))

# Drop junk/distractor rows before anything else touches the data.
df_train_clean = df_train[~df_train.person_id.isin([0, -1])].reset_index(drop=True)
df_gallery_eval = df_gallery.copy()   # keep junk/distractor in gallery -- they are needed
                                       # for the evaluation protocol itself (see Section 14),
                                       # they're just never allowed to count as a "correct match".
df_query_clean = df_query[~df_query.person_id.isin([0, -1])].reset_index(drop=True)

print("Clean train images:", len(df_train_clean), "| identities:", df_train_clean.person_id.nunique())
print("Clean query images:", len(df_query_clean), "| identities:", df_query_clean.person_id.nunique())

"""## 10. Exploratory Data Analysis"""

fig, axes = plt.subplots(1, 3, figsize=(18, 4))

imgs_per_id = df_train_clean.groupby("person_id").size()
axes[0].hist(imgs_per_id, bins=30, color="#4C72B0")
axes[0].set_title("Train: images per identity")
axes[0].set_xlabel("images"); axes[0].set_ylabel("num identities")

cam_counts = df_train_clean.camera_id.value_counts().sort_index()
axes[1].bar(cam_counts.index.astype(str), cam_counts.values, color="#55A868")
axes[1].set_title("Train: images per camera")
axes[1].set_xlabel("camera id"); axes[1].set_ylabel("num images")

cams_per_id = df_train_clean.groupby("person_id").camera_id.nunique()
axes[2].hist(cams_per_id, bins=range(1, 8), align="left", color="#C44E52")
axes[2].set_title("Train: distinct cameras seen per identity")
axes[2].set_xlabel("num distinct cameras"); axes[2].set_ylabel("num identities")

plt.tight_layout(); plt.show()

print("Median images/identity (train):", imgs_per_id.median())
print("Identities seen in only 1 camera (train):", (cams_per_id == 1).sum(),
      "-- these contribute nothing to cross-camera Re-ID learning and are worth knowing about.")

# Visual sanity check: same identity across different cameras should look like the same person.
sample_id = imgs_per_id[imgs_per_id >= 4].sample(1, random_state=SEED).index[0]
sample_rows = df_train_clean[df_train_clean.person_id == sample_id].sort_values("camera_id").head(6)

fig, axes = plt.subplots(1, len(sample_rows), figsize=(3 * len(sample_rows), 3.5))
if len(sample_rows) == 1:
    axes = [axes]
for ax, (_, row) in zip(axes, sample_rows.iterrows()):
    ax.imshow(Image.open(row.path))
    ax.set_title(f"ID {row.person_id}\ncam {row.camera_id}")
    ax.axis("off")
plt.suptitle(f"Sample identity {sample_id} across cameras")
plt.tight_layout(); plt.show()

# Random grid of distinct identities -- eyeball diversity of clothing/pose (relevant to
# whether the augmentation choices below make sense for this data).
rand_ids = np.random.RandomState(SEED).choice(df_train_clean.person_id.unique(), size=8, replace=False)
fig, axes = plt.subplots(1, 8, figsize=(20, 3))
for ax, pid in zip(axes, rand_ids):
    row = df_train_clean[df_train_clean.person_id == pid].iloc[0]
    ax.imshow(Image.open(row.path)); ax.set_title(f"ID {pid}"); ax.axis("off")
plt.suptitle("Random distinct identities")
plt.tight_layout(); plt.show()

"""## 11. Preprocessing & Augmentation

**Preprocessing:** resize to the standard Re-ID input size (256×128, matching the aspect ratio of a
pedestrian bounding box — not square, since squashing a tall/thin person crop into a square distorts the
exact silhouette cues the model relies on), then normalize with ImageNet mean/std since the backbone is
ImageNet-pretrained.

**Augmentation (train only) — each one chosen for a concrete reason, not by default:**
- **Random horizontal flip** — camera angle is arbitrary; a person's identity doesn't depend on which way
  they're facing the camera.
- **Padding + random crop** — standard Re-ID augmentation, adds translation robustness (crops from
  CCTV/detector boxes are rarely perfectly centered).
- **Color jitter (mild)** — CCTV footage across different cameras has different exposure/white balance;
  small brightness/contrast/saturation jitter reduces over-fitting to one camera's colour profile.
- **Random Erasing** — this is the most important one for VariSetu specifically: it randomly blanks out a
  rectangular patch of the image during training, forcing the model to not rely on any single body region.
  This directly simulates the **partial occlusion that is the norm in a dense pilgrim crowd** (an arm, a
  flag, another pilgrim's shoulder blocking part of the body) — the real deployment condition this model
  needs to be robust to, more so than a controlled campus-CCTV benchmark naturally contains.

No augmentation is applied to query/gallery/validation images — evaluation must reflect real inference-time
input, not augmented input.
"""

IMG_SIZE = (256, 128)   # (height, width) -- standard Re-ID aspect ratio
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_transform = T.Compose([
    T.Resize(IMG_SIZE),
    T.Pad(10),
    T.RandomCrop(IMG_SIZE),
    T.RandomHorizontalFlip(p=0.5),
    T.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.1, hue=0.02),
    T.ToTensor(),
    T.Normalize(IMAGENET_MEAN, IMAGENET_STD),
    T.RandomErasing(p=0.5, scale=(0.02, 0.2), ratio=(0.3, 3.3), value="random"),
])

eval_transform = T.Compose([
    T.Resize(IMG_SIZE),
    T.ToTensor(),
    T.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

# Visualize augmentation effect on one real sample image
sample_path = df_train_clean.iloc[0].path
orig = Image.open(sample_path)

denorm = T.Normalize(mean=[-m/s for m, s in zip(IMAGENET_MEAN, IMAGENET_STD)],
                      std=[1/s for s in IMAGENET_STD])

fig, axes = plt.subplots(1, 6, figsize=(18, 3.2))
axes[0].imshow(orig); axes[0].set_title("original"); axes[0].axis("off")
for i in range(1, 6):
    aug_t = train_transform(orig)
    aug_img = denorm(aug_t).clamp(0, 1).permute(1, 2, 0).numpy()
    axes[i].imshow(aug_img); axes[i].set_title(f"augmented #{i}"); axes[i].axis("off")
plt.suptitle("Augmentation preview (flip / pad-crop / jitter / random erasing)")
plt.tight_layout(); plt.show()

"""## 12. Train / Held-out Split

Market-1501's `train` and `query+gallery` sets already use **disjoint identities** (751 vs. 750, verified
above) — this is the correct open-set protocol and is why the Query/Gallery evaluation in Section 15 is the
real measure of generalization.

For the auxiliary **ID-classification metrics** requested (accuracy/precision/recall/F1), we carve a small
**held-out split from the train set only** (same identities, unseen images) purely to monitor whether the
classification head is learning sensibly during training — this is a closed-set sanity check, not a
substitute for the open-set Query/Gallery evaluation, and the notebook is explicit about that distinction
throughout.
"""

# Remap raw person_id (sparse, non-contiguous) -> contiguous class index for the classifier head
unique_train_ids = sorted(df_train_clean.person_id.unique())
pid_to_label = {pid: i for i, pid in enumerate(unique_train_ids)}
label_to_pid = {i: pid for pid, i in pid_to_label.items()}
NUM_TRAIN_CLASSES = len(unique_train_ids)
print("Num train classes (identities):", NUM_TRAIN_CLASSES)

df_train_clean["label"] = df_train_clean.person_id.map(pid_to_label)

# Stratified per-identity held-out split: for every identity with >=2 images, hold out ~15% of its
# images (at least 1) for monitoring. Identities with only 1 image stay fully in train (can't split
# them without losing that class entirely from training).
rng = np.random.RandomState(SEED)
val_idx = []
for pid, group in df_train_clean.groupby("person_id"):
    n = len(group)
    if n < 2:
        continue
    n_val = max(1, int(round(n * 0.15)))
    val_rows = group.sample(n=n_val, random_state=SEED)
    val_idx.extend(val_rows.index.tolist())

df_val_split = df_train_clean.loc[val_idx].reset_index(drop=True)
df_train_split = df_train_clean.drop(index=val_idx).reset_index(drop=True)

print("Train split:", len(df_train_split), "images |", df_train_split.person_id.nunique(), "identities")
print("Held-out split:", len(df_val_split), "images |", df_val_split.person_id.nunique(), "identities")
assert set(df_train_split.person_id) == set(df_train_clean.person_id), \
    "A whole identity was accidentally dropped from training -- fix the split logic before continuing."

"""## 13. Dataset / DataLoader classes"""

class ReIDImageDataset(Dataset):
    """Generic image + label dataset for the classification-monitored train/val splits."""
    def __init__(self, df, transform):
        self.df = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row.path).convert("RGB")
        img = self.transform(img)
        return img, int(row.label), row.person_id, row.camera_id


class ReIDEvalDataset(Dataset):
    """Query/Gallery dataset -- no class labels needed for the model input, we keep
    person_id/camera_id alongside purely for the retrieval evaluation protocol."""
    def __init__(self, df, transform):
        self.df = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row.path).convert("RGB")
        img = self.transform(img)
        return img, int(row.person_id), int(row.camera_id)


class PKSampler(Sampler):
    """Batch-hard triplet loss needs P identities x K images-per-identity per batch, not a
    plain random shuffle, or there may be zero valid triplets in a batch."""
    def __init__(self, df, num_ids_per_batch=16, num_imgs_per_id=4):
        self.df = df
        self.P = num_ids_per_batch
        self.K = num_imgs_per_id
        self.id_to_indices = defaultdict(list)
        for idx, pid in enumerate(df.person_id.values):
            self.id_to_indices[pid].append(idx)
        self.pids = [pid for pid, idxs in self.id_to_indices.items() if len(idxs) >= 1]
        self.length = (len(self.pids) // self.P) * self.P * self.K

    def __iter__(self):
        pids = self.pids.copy()
        random.shuffle(pids)
        batches = []
        for i in range(0, len(pids) - self.P + 1, self.P):
            batch_pids = pids[i:i + self.P]
            batch = []
            for pid in batch_pids:
                idxs = self.id_to_indices[pid]
                if len(idxs) >= self.K:
                    chosen = random.sample(idxs, self.K)
                else:
                    chosen = random.choices(idxs, k=self.K)   # sample with replacement if too few
                batch.extend(chosen)
            batches.append(batch)
        random.shuffle(batches)
        flat = [i for b in batches for i in b]
        return iter(flat)

    def __len__(self):
        return self.length


BATCH_P = 16   # identities per batch
BATCH_K = 4    # images per identity per batch -> batch size = 64
NUM_WORKERS = 2

train_ds = ReIDImageDataset(df_train_split, train_transform)
val_ds   = ReIDImageDataset(df_val_split, eval_transform)

train_sampler = PKSampler(df_train_split, num_ids_per_batch=BATCH_P, num_imgs_per_id=BATCH_K)
train_loader = DataLoader(train_ds, batch_size=BATCH_P * BATCH_K, sampler=train_sampler,
                           num_workers=NUM_WORKERS, drop_last=True)
val_loader = DataLoader(val_ds, batch_size=128, shuffle=False, num_workers=NUM_WORKERS)

print("Train batches per epoch:", len(train_loader), "| Val images:", len(val_ds))

"""## 14. Model & Losses

**Backbone:** ResNet-50, ImageNet-pretrained (transfer learning — training a CNN from scratch on ~11K train
images would badly overfit; ImageNet features transfer well to person imagery).

**BNNeck:** a BatchNorm1d layer (no bias) between the pooled feature and the classifier. This is the single
highest-value trick from the "Bag of Tricks" Re-ID baseline: the **pre-BN feature** is used for the triplet
loss (keeps it well-clustered by cosine similarity) and the **post-BN feature** is used for classification —
using one shared feature for both losses measurably hurts Re-ID performance because the two losses pull the
same feature space in different directions.

**Loss = Cross-Entropy (label smoothing 0.1) + Batch-Hard Triplet Loss (margin 0.3).**
- CE trains the identity-classification head (gives us accuracy/precision/recall/F1 during training).
- Triplet loss directly optimizes what the deployed system needs: same-identity embeddings pulled together,
  different-identity embeddings pushed apart, using the hardest positive/negative in each PK-batch.
"""

class ReIDModel(nn.Module):
    def __init__(self, num_classes, embedding_dim=2048):
        super().__init__()
        backbone = resnet50(weights=ResNet50_Weights.IMAGENET1K_V2)
        # Standard Re-ID trick: drop the stride in the last residual stage so the final
        # feature map has more spatial resolution (helps with small/occluded person crops).
        backbone.layer4[0].downsample[0].stride = (1, 1)
        backbone.layer4[0].conv2.stride = (1, 1)
        self.backbone = nn.Sequential(*list(backbone.children())[:-2])  # drop avgpool+fc
        self.gap = nn.AdaptiveAvgPool2d(1)
        self.bnneck = nn.BatchNorm1d(embedding_dim)
        self.bnneck.bias.requires_grad_(False)   # no-bias BNNeck, per Bag-of-Tricks
        self.classifier = nn.Linear(embedding_dim, num_classes, bias=False)

    def forward(self, x):
        feat_map = self.backbone(x)
        pooled = self.gap(feat_map).flatten(1)         # pre-BN embedding (for triplet loss / inference)
        bn_feat = self.bnneck(pooled)                   # post-BN embedding (for classification)
        logits = self.classifier(bn_feat)
        return pooled, bn_feat, logits


class BatchHardTripletLoss(nn.Module):
    def __init__(self, margin=0.3):
        super().__init__()
        self.margin = margin

    def forward(self, embeddings, labels):
        # pairwise Euclidean distance matrix
        dist = torch.cdist(embeddings, embeddings, p=2)
        labels = labels.unsqueeze(1)
        same = labels.eq(labels.t())
        diff = ~same

        # hardest positive: max distance among same-identity pairs (excluding self)
        dist_pos = dist.clone()
        dist_pos[~same] = -1
        dist_pos.fill_diagonal_(-1)
        hardest_pos = dist_pos.max(dim=1).values

        # hardest negative: min distance among different-identity pairs
        dist_neg = dist.clone()
        dist_neg[same] = float("inf")
        hardest_neg = dist_neg.min(dim=1).values

        loss = F.relu(hardest_pos - hardest_neg + self.margin)
        return loss.mean()


EMBEDDING_DIM = 2048
model = ReIDModel(num_classes=NUM_TRAIN_CLASSES, embedding_dim=EMBEDDING_DIM).to(DEVICE)

ce_loss_fn = nn.CrossEntropyLoss(label_smoothing=0.1)
triplet_loss_fn = BatchHardTripletLoss(margin=0.3)

optimizer = torch.optim.Adam(model.parameters(), lr=3.5e-4, weight_decay=5e-4)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=15, gamma=0.1)

TRIPLET_WEIGHT = 1.0   # combined_loss = ce_loss + TRIPLET_WEIGHT * triplet_loss

n_params = sum(p.numel() for p in model.parameters())
print(f"Model parameters: {n_params/1e6:.1f}M")

"""## 15. Baseline (before training)

A quick sanity baseline: run the **ImageNet-pretrained backbone with no Re-ID fine-tuning** through the
same evaluation pipeline used later, so the trained model's improvement is measured against something real
rather than assumed.
"""

@torch.no_grad()
def extract_embeddings(model, dataset, batch_size=128):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS)
    model.eval()
    all_embeds, all_pids, all_camids = [], [], []
    for imgs, pids, camids in loader:
        imgs = imgs.to(DEVICE)
        pooled, bn_feat, _ = model(imgs)
        embed = F.normalize(pooled, dim=1)   # cosine-ready embedding (pre-BN, per Bag-of-Tricks)
        all_embeds.append(embed.cpu().numpy())
        all_pids.append(np.array(pids))
        all_camids.append(np.array(camids))
    return (np.concatenate(all_embeds), np.concatenate(all_pids), np.concatenate(all_camids))


def evaluate_cmc_map(q_embed, q_pids, q_camids, g_embed, g_pids, g_camids, ranks=(1, 5, 10)):
    """Standard Market-1501 CMC/mAP protocol: for each query, rank all gallery images by
    cosine distance, but SKIP gallery entries that are junk (pid==0), distractor (pid==-1),
    or the exact same identity captured by the exact same camera (that would be a trivial
    'match' of the same physical photo series, not a genuine cross-camera re-identification)."""
    sim = q_embed @ g_embed.T
    dist = 1 - sim
    num_q = dist.shape[0]

    all_cmc, all_ap = [], []
    for i in range(num_q):
        order = np.argsort(dist[i])
        g_pids_sorted = g_pids[order]
        g_camids_sorted = g_camids[order]

        valid = ~(((g_pids_sorted == q_pids[i]) & (g_camids_sorted == q_camids[i])) |
                  (g_pids_sorted == 0) | (g_pids_sorted == -1))
        g_pids_valid = g_pids_sorted[valid]

        matches = (g_pids_valid == q_pids[i]).astype(np.int32)
        if matches.sum() == 0:
            continue   # no valid ground truth for this query, skip (standard protocol)

        cmc = matches.cumsum()
        cmc[cmc > 1] = 1
        all_cmc.append(cmc[:max(ranks)])

        num_rel = matches.sum()
        tmp_cmc = matches.cumsum()
        precision_at_k = tmp_cmc / (np.arange(len(matches)) + 1)
        ap = (precision_at_k * matches).sum() / num_rel
        all_ap.append(ap)

    all_cmc = np.array(all_cmc)
    cmc_curve = all_cmc.mean(axis=0)
    result = {f"Rank-{r}": cmc_curve[r - 1] for r in ranks}
    result["mAP"] = float(np.mean(all_ap))
    result["_cmc_curve"] = cmc_curve
    return result


query_eval_ds = ReIDEvalDataset(df_query_clean, eval_transform)
gallery_eval_ds = ReIDEvalDataset(df_gallery_eval, eval_transform)

print("Extracting baseline (untrained head, ImageNet-only) embeddings ...")
q_embed_base, q_pid_base, q_cam_base = extract_embeddings(model, query_eval_ds)
g_embed_base, g_pid_base, g_cam_base = extract_embeddings(model, gallery_eval_ds)
baseline_results = evaluate_cmc_map(q_embed_base, q_pid_base, q_cam_base,
                                     g_embed_base, g_pid_base, g_cam_base)
print("Baseline (pretrained-only, no Re-ID training):")
for k, v in baseline_results.items():
    if not k.startswith("_"):
        print(f"  {k}: {v:.4f}")

"""## 16. Training Loop"""

def run_epoch_train(model, loader, optimizer):
    model.train()
    total_loss, total_ce, total_tri = 0.0, 0.0, 0.0
    all_preds, all_labels = [], []

    for imgs, labels, pids, camids in loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        pooled, bn_feat, logits = model(imgs)

        ce = ce_loss_fn(logits, labels)
        tri = triplet_loss_fn(pooled, labels)
        loss = ce + TRIPLET_WEIGHT * tri

        loss.backward()
        optimizer.step()

        total_loss += loss.item() * imgs.size(0)
        total_ce += ce.item() * imgs.size(0)
        total_tri += tri.item() * imgs.size(0)
        all_preds.append(logits.argmax(dim=1).detach().cpu().numpy())
        all_labels.append(labels.detach().cpu().numpy())

    n = len(loader.dataset) if hasattr(loader, "dataset") else len(all_labels) * loader.batch_size
    n = sum(len(l) for l in all_labels)
    y_true = np.concatenate(all_labels); y_pred = np.concatenate(all_preds)
    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="macro", zero_division=0)
    return {"loss": total_loss / n, "ce_loss": total_ce / n, "triplet_loss": total_tri / n,
            "accuracy": acc, "precision_macro": prec, "recall_macro": rec, "f1_macro": f1}


@torch.no_grad()
def run_epoch_val(model, loader):
    model.eval()
    all_preds, all_labels = [], []
    total_ce = 0.0
    for imgs, labels, pids, camids in loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        pooled, bn_feat, logits = model(imgs)
        ce = ce_loss_fn(logits, labels)
        total_ce += ce.item() * imgs.size(0)
        all_preds.append(logits.argmax(dim=1).cpu().numpy())
        all_labels.append(labels.cpu().numpy())
    y_true = np.concatenate(all_labels); y_pred = np.concatenate(all_preds)
    acc = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="macro", zero_division=0)
    return {"ce_loss": total_ce / len(y_true), "accuracy": acc,
            "precision_macro": prec, "recall_macro": rec, "f1_macro": f1}

NUM_EPOCHS = 60   # adjust upward (e.g. 60-120) for a longer, higher-accuracy Colab run if time/GPU allow

history = {"train": [], "val": []}

for epoch in range(1, NUM_EPOCHS + 1):
    t0 = time.time()
    train_metrics = run_epoch_train(model, train_loader, optimizer)
    val_metrics = run_epoch_val(model, val_loader)
    scheduler.step()

    history["train"].append(train_metrics)
    history["val"].append(val_metrics)

    print(f"Epoch {epoch:03d}/{NUM_EPOCHS} ({time.time()-t0:.1f}s) | "
          f"train loss {train_metrics['loss']:.3f} (ce {train_metrics['ce_loss']:.3f}, "
          f"tri {train_metrics['triplet_loss']:.3f}) | "
          f"train acc {train_metrics['accuracy']:.3f} f1 {train_metrics['f1_macro']:.3f} | "
          f"val acc {val_metrics['accuracy']:.3f} f1 {val_metrics['f1_macro']:.3f}")

"""## 17. Training Curves"""

epochs = range(1, NUM_EPOCHS + 1)
fig, axes = plt.subplots(1, 3, figsize=(18, 4.5))

axes[0].plot(epochs, [h["loss"] for h in history["train"]], label="train total loss")
axes[0].plot(epochs, [h["ce_loss"] for h in history["train"]], label="train CE loss", linestyle="--")
axes[0].plot(epochs, [h["triplet_loss"] for h in history["train"]], label="train triplet loss", linestyle="--")
axes[0].set_title("Loss"); axes[0].set_xlabel("epoch"); axes[0].legend()

axes[1].plot(epochs, [h["accuracy"] for h in history["train"]], label="train accuracy")
axes[1].plot(epochs, [h["accuracy"] for h in history["val"]], label="held-out accuracy")
axes[1].set_title("ID-Classification Accuracy (closed-set)"); axes[1].set_xlabel("epoch"); axes[1].legend()

axes[2].plot(epochs, [h["f1_macro"] for h in history["train"]], label="train F1 (macro)")
axes[2].plot(epochs, [h["f1_macro"] for h in history["val"]], label="held-out F1 (macro)")
axes[2].plot(epochs, [h["precision_macro"] for h in history["val"]], label="held-out precision (macro)", linestyle=":")
axes[2].plot(epochs, [h["recall_macro"] for h in history["val"]], label="held-out recall (macro)", linestyle=":")
axes[2].set_title("Precision / Recall / F1 (macro, closed-set)"); axes[2].set_xlabel("epoch"); axes[2].legend()

plt.tight_layout(); plt.show()

final_val = history["val"][-1]
print("Final held-out (closed-set) metrics:")
for k, v in final_val.items():
    print(f"  {k}: {v:.4f}")

"""## 18. Full Re-ID Evaluation — CMC & mAP (the metric that actually matters for deployment)

This is evaluated on **Query vs. Gallery**, identities the model never saw a classification label for
during training (open-set) — the honest measure of "can this system find the right person in a camera it
hasn't matched them in before."
"""

print("Extracting trained embeddings ...")
q_embed, q_pid, q_cam = extract_embeddings(model, query_eval_ds)
g_embed, g_pid, g_cam = extract_embeddings(model, gallery_eval_ds)

trained_results = evaluate_cmc_map(q_embed, q_pid, q_cam, g_embed, g_pid, g_cam)

print("\n=== Trained model: Re-ID retrieval performance ===")
for k, v in trained_results.items():
    if not k.startswith("_"):
        print(f"  {k}: {v:.4f}")

print("\n=== Comparison vs. pretrained-only baseline ===")
comparison = pd.DataFrame({
    "Baseline (ImageNet only)": {k: v for k, v in baseline_results.items() if not k.startswith("_")},
    "Trained (Re-ID fine-tuned)": {k: v for k, v in trained_results.items() if not k.startswith("_")},
})
comparison

ranks_x = np.arange(1, len(trained_results["_cmc_curve"]) + 1)
plt.figure(figsize=(7, 5))
plt.plot(ranks_x, baseline_results["_cmc_curve"], marker="o", label="Baseline (ImageNet only)")
plt.plot(ranks_x, trained_results["_cmc_curve"], marker="o", label="Trained (Re-ID fine-tuned)")
plt.xlabel("Rank"); plt.ylabel("Cumulative Matching Accuracy")
plt.title("CMC Curve (Query vs. Gallery, Market-1501 protocol)")
plt.ylim(0, 1.02); plt.legend(); plt.grid(alpha=0.3)
plt.show()

"""## 19. Verification (Same/Different Person) — ROC-AUC

Reframing Re-ID as **pairwise verification** is the one place ROC-AUC is actually meaningful here: given two
person-crop embeddings, is this the *same* physical person (positive) or *different* people (negative)?
This mirrors what the control-room officer confirmation step does in practice, and it's the metric that
maps most directly onto "how often would the system produce a confusing false-positive suggestion."

Pairs are sampled from Query+Gallery embeddings (never from train) so this, like CMC/mAP, is an open-set
measurement.
"""

def sample_verification_pairs(embed, pids, camids, num_pos=5000, num_neg=5000, seed=SEED):
    rng = np.random.RandomState(seed)
    n = len(pids)
    pid_to_idx = defaultdict(list)
    for i, pid in enumerate(pids):
        if pid in (0, -1):
            continue
        pid_to_idx[pid].append(i)
    valid_pids = [p for p, idxs in pid_to_idx.items() if len(idxs) >= 2]

    pos_scores, neg_scores = [], []

    # Positive pairs: same identity, different image (ideally different camera)
    while len(pos_scores) < num_pos:
        pid = rng.choice(valid_pids)
        i, j = rng.choice(pid_to_idx[pid], size=2, replace=False)
        pos_scores.append(float(embed[i] @ embed[j]))

    # Negative pairs: different identities
    all_valid_idx = [i for i, p in enumerate(pids) if p not in (0, -1)]
    while len(neg_scores) < num_neg:
        i, j = rng.choice(all_valid_idx, size=2, replace=False)
        if pids[i] != pids[j]:
            neg_scores.append(float(embed[i] @ embed[j]))

    scores = np.array(pos_scores + neg_scores)
    labels = np.array([1] * len(pos_scores) + [0] * len(neg_scores))   # 1 = same person
    return scores, labels


combined_embed = np.concatenate([q_embed, g_embed])
combined_pid = np.concatenate([q_pid, g_pid])
combined_cam = np.concatenate([q_cam, g_cam])

ver_scores, ver_labels = sample_verification_pairs(combined_embed, combined_pid, combined_cam,
                                                     num_pos=5000, num_neg=5000)

fpr, tpr, thresholds = roc_curve(ver_labels, ver_scores)
roc_auc = auc(fpr, tpr)
print(f"Verification ROC-AUC: {roc_auc:.4f}  (on {len(ver_labels)} sampled same/different pairs)")

plt.figure(figsize=(6, 6))
plt.plot(fpr, tpr, label=f"ROC (AUC = {roc_auc:.4f})")
plt.plot([0, 1], [0, 1], linestyle="--", color="gray", label="chance")
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("Verification ROC Curve (same-person vs. different-person)")
plt.legend(); plt.grid(alpha=0.3)
plt.show()

# Pick an operating threshold for the deployed system: prioritize a LOW false-positive rate,
# since a false "same person" suggestion sends a control-room officer chasing the wrong pilgrim.
# Report Precision/Recall/F1 (binary, "same person" = positive class) at this chosen threshold.
target_fpr = 0.05
idx = np.argmin(np.abs(fpr - target_fpr))
chosen_threshold = thresholds[idx]
ver_preds_at_threshold = (ver_scores >= chosen_threshold).astype(int)

prec_v, rec_v, f1_v, _ = precision_recall_fscore_support(ver_labels, ver_preds_at_threshold,
                                                            average="binary", zero_division=0)
acc_v = accuracy_score(ver_labels, ver_preds_at_threshold)
print(f"\nAt threshold {chosen_threshold:.4f} (targeting ~{target_fpr:.0%} FPR):")
print(f"  Accuracy: {acc_v:.4f} | Precision: {prec_v:.4f} | Recall: {rec_v:.4f} | F1: {f1_v:.4f}")

"""## 20. Confusion Matrix (illustrative subset)

A full 751-class confusion matrix is unreadable and not useful for a demo. Instead: pick the **20 most
frequent train identities** and show a genuine confusion matrix over just those, on their held-out images —
readable, and still an honest (if partial) view of where the classifier confuses similar-looking
identities.
"""

top_ids = df_train_split.person_id.value_counts().head(20).index.tolist()
top_labels = [pid_to_label[pid] for pid in top_ids]

mask_val = df_val_split.person_id.isin(top_ids)
df_val_top = df_val_split[mask_val].reset_index(drop=True)

if len(df_val_top) > 5:
    val_top_ds = ReIDImageDataset(df_val_top, eval_transform)
    val_top_loader = DataLoader(val_top_ds, batch_size=64, shuffle=False)

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for imgs, labels, pids, camids in val_top_loader:
            imgs = imgs.to(DEVICE)
            _, _, logits = model(imgs)
            y_pred.append(logits.argmax(dim=1).cpu().numpy())
            y_true.append(labels.numpy())
    y_true = np.concatenate(y_true); y_pred = np.concatenate(y_pred)

    cm = confusion_matrix(y_true, y_pred, labels=top_labels)
    fig, ax = plt.subplots(figsize=(9, 8))
    disp = ConfusionMatrixDisplay(cm, display_labels=[f"ID{label_to_pid[l]}" for l in top_labels])
    disp.plot(ax=ax, cmap="Blues", xticks_rotation=90, colorbar=False)
    plt.title("Confusion Matrix -- 20 most-frequent identities (held-out images)")
    plt.tight_layout(); plt.show()
else:
    print("Not enough held-out images among the top-20 identities to draw a meaningful confusion matrix.")

"""## 21. Embedding Space Visualization (t-SNE)"""

from sklearn.manifold import TSNE

vis_ids = np.random.RandomState(SEED).choice(list(set(g_pid) - {0, -1}), size=15, replace=False)
mask = np.isin(g_pid, vis_ids)
vis_embed = g_embed[mask]
vis_pid = g_pid[mask]

tsne = TSNE(n_components=2, random_state=SEED, perplexity=30, init="pca")
vis_2d = tsne.fit_transform(vis_embed)

plt.figure(figsize=(9, 8))
palette = sns.color_palette("husl", len(vis_ids))
for color, pid in zip(palette, vis_ids):
    pts = vis_2d[vis_pid == pid]
    plt.scatter(pts[:, 0], pts[:, 1], color=color, label=f"ID {pid}", s=40, alpha=0.8)
plt.title("t-SNE of gallery embeddings -- 15 random identities")
plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
plt.tight_layout(); plt.show()
print("Tight, well-separated clusters per identity = the embedding space is doing its job. "
      "Overlapping clusters point to identities the model still confuses (e.g. very similar clothing).")

"""## 22. Sample Retrieval Results — Explainability"""

def show_retrieval(query_idx, k=5):
    q_row = df_query_clean.iloc[query_idx]
    q_vec = q_embed[query_idx]
    sims = g_embed @ q_vec
    dists = 1 - sims
    order = np.argsort(dists)

    valid_order = [o for o in order
                   if not ((g_pid[o] == q_row.person_id and g_cam[o] == q_row.camera_id)
                           or g_pid[o] in (0, -1))][:k]

    fig, axes = plt.subplots(1, k + 1, figsize=(3 * (k + 1), 3.5))
    axes[0].imshow(Image.open(q_row.path)); axes[0].set_title(f"QUERY\nID {q_row.person_id}")
    axes[0].axis("off")
    for ax, gi in zip(axes[1:], valid_order):
        g_row = df_gallery_eval.iloc[gi]
        correct = (g_pid[gi] == q_row.person_id)
        ax.imshow(Image.open(g_row.path))
        ax.set_title(f"{'CORRECT' if correct else 'wrong'}\nID {g_pid[gi]} (d={dists[gi]:.3f})",
                     color="green" if correct else "red")
        ax.axis("off")
    plt.suptitle("Top-5 retrieval results for one query")
    plt.tight_layout(); plt.show()

for qi in np.random.RandomState(SEED).choice(len(df_query_clean), size=3, replace=False):
    show_retrieval(int(qi), k=5)

"""## 23. Final Training Note

The training run above (Section 16) **is** the final training run for this baseline — there is no separate
"candidate models" comparison stage for this notebook, because for Re-ID with a fixed, well-established
strong-baseline architecture (ResNet50 + BNNeck + CE+Triplet), the meaningful lever is training
duration/hyperparameters, not swapping architectures. If Rank-1/mAP after `NUM_EPOCHS` above are
unsatisfactory, the first thing to try is **increasing `NUM_EPOCHS`** (60–120 is typical for Market-1501 in
the literature) before changing architecture — noted here rather than silently re-running with different
settings and only reporting the best one.

## 24. Model Export
"""

import datetime

EXPORT_DIR = "/content/varisetu_reid_artifacts"
os.makedirs(EXPORT_DIR, exist_ok=True)

# 1) Model weights
torch.save(model.state_dict(), os.path.join(EXPORT_DIR, "reid_model.pt"))

# 2) Preprocessing + metadata config -- everything the standalone inference.py needs,
#    with NOTHING hard-coded on the backend side.
config = {
    "model_name": "varisetu_person_reid",
    "backbone": "resnet50_imagenet_pretrained",
    "embedding_dim": EMBEDDING_DIM,
    "img_size": {"height": IMG_SIZE[0], "width": IMG_SIZE[1]},
    "normalize_mean": IMAGENET_MEAN,
    "normalize_std": IMAGENET_STD,
    "num_train_classes": NUM_TRAIN_CLASSES,
    "label_to_person_id": {str(k): int(v) for k, v in label_to_pid.items()},
    "embedding_used_for_inference": "pre_bn_pooled_l2_normalized",
    "similarity_metric": "cosine",
    "verification_threshold_at_5pct_fpr": float(chosen_threshold),
    "trained_epochs": NUM_EPOCHS,
    "dataset": "Market-1501 (pengcw1/market-1501, Kaggle mirror)",
    "exported_at_utc": datetime.datetime.utcnow().isoformat(),
    "final_metrics": {
        "rank1": float(trained_results["Rank-1"]),
        "rank5": float(trained_results["Rank-5"]),
        "rank10": float(trained_results["Rank-10"]),
        "mAP": float(trained_results["mAP"]),
        "verification_roc_auc": float(roc_auc),
        "held_out_classification_accuracy": float(final_val["accuracy"]),
        "held_out_classification_f1_macro": float(final_val["f1_macro"]),
    },
}
with open(os.path.join(EXPORT_DIR, "model_config.json"), "w") as f:
    json.dump(config, f, indent=2)

print("Exported artifacts to:", EXPORT_DIR)
print(os.listdir(EXPORT_DIR))

# Download from Colab
from google.colab import files
import shutil

zip_path = shutil.make_archive("/content/varisetu_reid_artifacts", "zip", EXPORT_DIR)
print("Zipped artifacts:", zip_path)
files.download(zip_path)

"""## 25. Reload Saved Model & Verify"""

with open(os.path.join(EXPORT_DIR, "model_config.json")) as f:
    loaded_config = json.load(f)

reloaded_model = ReIDModel(num_classes=loaded_config["num_train_classes"],
                            embedding_dim=loaded_config["embedding_dim"]).to(DEVICE)
reloaded_model.load_state_dict(torch.load(os.path.join(EXPORT_DIR, "reid_model.pt"), map_location=DEVICE))
reloaded_model.eval()
print("Reloaded model successfully.")

# Verify: re-run the query/gallery embedding extraction + CMC/mAP with the RELOADED model and
# confirm it matches the pre-export results -- this is the actual "does the saved artifact work" test.
rq_embed, rq_pid, rq_cam = extract_embeddings(reloaded_model, query_eval_ds)
rg_embed, rg_pid, rg_cam = extract_embeddings(reloaded_model, gallery_eval_ds)
reload_results = evaluate_cmc_map(rq_embed, rq_pid, rq_cam, rg_embed, rg_pid, rg_cam)

print("\nOriginal in-memory model  vs.  Reloaded-from-disk model:")
for k in ["Rank-1", "Rank-5", "Rank-10", "mAP"]:
    print(f"  {k}: {trained_results[k]:.4f}  vs.  {reload_results[k]:.4f}  "
          f"(match: {np.isclose(trained_results[k], reload_results[k])})")

"""## 26. Standalone Inference Test"""

def load_reid_inference(export_dir, device=None):
    """Everything a backend needs to call, independent of this notebook."""
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    with open(os.path.join(export_dir, "model_config.json")) as f:
        cfg = json.load(f)

    m = ReIDModel(num_classes=cfg["num_train_classes"], embedding_dim=cfg["embedding_dim"]).to(device)
    m.load_state_dict(torch.load(os.path.join(export_dir, "reid_model.pt"), map_location=device))
    m.eval()

    tfm = T.Compose([
        T.Resize((cfg["img_size"]["height"], cfg["img_size"]["width"])),
        T.ToTensor(),
        T.Normalize(cfg["normalize_mean"], cfg["normalize_std"]),
    ])

    @torch.no_grad()
    def embed_image(pil_image):
        x = tfm(pil_image.convert("RGB")).unsqueeze(0).to(device)
        pooled, _, _ = m(x)
        return F.normalize(pooled, dim=1).cpu().numpy()[0]

    return embed_image, cfg


embed_fn, cfg = load_reid_inference(EXPORT_DIR)

# Independent end-to-end test: embed a query image and a same-identity gallery image from disk,
# using ONLY the standalone inference function (no reuse of q_embed/g_embed computed earlier).
test_query_row = df_query_clean.iloc[0]
same_id_gallery_row = df_gallery_eval[
    (df_gallery_eval.person_id == test_query_row.person_id) &
    (df_gallery_eval.camera_id != test_query_row.camera_id)
].iloc[0]
diff_id_gallery_row = df_gallery_eval[df_gallery_eval.person_id != test_query_row.person_id].iloc[0]

v_query = embed_fn(Image.open(test_query_row.path))
v_same = embed_fn(Image.open(same_id_gallery_row.path))
v_diff = embed_fn(Image.open(diff_id_gallery_row.path))

print(f"Cosine similarity, SAME person (different camera): {float(v_query @ v_same):.4f}")
print(f"Cosine similarity, DIFFERENT people:                {float(v_query @ v_diff):.4f}")
print("\nExpected: same-person similarity should be clearly higher than different-person similarity.")

"""## 27. Conclusions

- **ML problem:** person re-identification — matching a missing pilgrim's appearance across CCTV cameras
  that have never seen that specific pairing before.
- **Approach:** ResNet-50 (ImageNet-pretrained) + BNNeck, trained with combined Cross-Entropy (label
  smoothing) + Batch-Hard Triplet loss on Market-1501, following the established "Bag of Tricks" strong
  Re-ID baseline.
- **Metrics reported, and why each is where it is:**
  - Accuracy / Precision / Recall / F1 (macro) — reported on the **closed-set ID-classification head**
    (Section 16–17), which is the only place these classification metrics are actually valid for a
    Re-ID model.
  - **Rank-1/5/10 and mAP** (Section 18) — the metrics that actually describe deployment performance:
    given a query, how often is the correct person found near the top of a ranked list from a camera it
    hasn't been matched from before.
  - **ROC-AUC** (Section 19) — reported on the **pairwise verification reframing** (same-person vs.
    different-person), the one place ROC-AUC is a meaningful measurement for a Re-ID system, plus a
    binary precision/recall/F1 at a chosen low-false-positive operating threshold.
- Numbers for all of the above are filled in only after you run this notebook in Colab — see the printed
  output of Sections 17–19 for your actual run's results.

## 28. Limitations

1. **Domain gap:** Market-1501 is campus pedestrians, not pilgrims in Wari conditions (different clothing
   distribution — sarees, kurtas, Gandhi topis vs. Western campus wear; different crowd density; different
   camera heights/angles). Rank-1/mAP on Market-1501 should be read as "does this architecture and training
   recipe work at all," not as the number to expect on real Wari footage.
2. **No Wari-specific fine-tuning data exists publicly** (established in the earlier dataset-sourcing
   conversation for this project) — before real deployment, this model needs fine-tuning on genuine
   Wari-corridor CCTV crops, which requires either the district's cooperation or a controlled pilot capture
   with consent.
3. **This model finds visually similar people, not confirmed identity.** It surfaces ranked candidates for
   a control-room officer to confirm — exactly as your report's own risk-mitigation states — never an
   autonomous "found" decision.
4. **Clothing-based matching has an inherent limitation:** if two pilgrims wear visually similar
   traditional dress (common at a religious gathering), appearance-based Re-ID alone may not distinguish
   them; this is why the report's pretrained face-recognition path is kept as a secondary confirmation
   signal, not discarded — it becomes useful whenever a clear frontal face crop is available.
5. **This notebook was authored without GPU/Kaggle access in this environment** and has not been executed
   end-to-end here — run it in Colab and treat the first real run's printed metrics as ground truth, not
   any number written in this markdown.

"""