import enum
from datetime import datetime, timezone
from typing import Any, Dict
from pydantic import BaseModel, Field


class WebSocketEventType(str, enum.Enum):
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_UPDATED = "INCIDENT_UPDATED"
    CROWD_UPDATED = "CROWD_UPDATED"
    MEDICAL_ALERT_CREATED = "MEDICAL_ALERT_CREATED"
    MEDICAL_ALERT_UPDATED = "MEDICAL_ALERT_UPDATED"
    RESOURCE_DISPATCHED = "RESOURCE_DISPATCHED"
    RESOURCE_STATUS_CHANGED = "RESOURCE_STATUS_CHANGED"
    LOST_PERSON_MATCH_FOUND = "LOST_PERSON_MATCH_FOUND"
    LOST_PERSON_VERIFIED = "LOST_PERSON_VERIFIED"
    LOST_PERSON_REUNITED = "LOST_PERSON_REUNITED"
    ROUTE_CHANGED = "ROUTE_CHANGED"
    TICKER_EVENT = "TICKER_EVENT"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    ACTION_CREATED = "ACTION_CREATED"
    ACTION_APPROVAL_REQUIRED = "ACTION_APPROVAL_REQUIRED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_EXECUTING = "ACTION_EXECUTING"
    ACTION_SUCCEEDED = "ACTION_SUCCEEDED"
    ACTION_FAILED = "ACTION_FAILED"
    ACTION_CANCELLED = "ACTION_CANCELLED"
    DASHBOARD_REFRESH_REQUIRED = "DASHBOARD_REFRESH_REQUIRED"
    ANNOUNCEMENT_CREATED = "ANNOUNCEMENT_CREATED"
    ANNOUNCEMENT_BROADCAST = "ANNOUNCEMENT_BROADCAST"
    ROUTE_RECOMMENDATION_CREATED = "ROUTE_RECOMMENDATION_CREATED"
    RESOURCE_RECOMMENDATION_CREATED = "RESOURCE_RECOMMENDATION_CREATED"
    YATRA_POSITION_UPDATED = "YATRA_POSITION_UPDATED"
    YATRA_ENTERED_ZONE = "YATRA_ENTERED_ZONE"
    YATRA_EXITED_ZONE = "YATRA_EXITED_ZONE"
    HEATMAP_UPDATED = "HEATMAP_UPDATED"


class WebSocketMessage(BaseModel):
    event: WebSocketEventType
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    data: Dict[str, Any]
