# -*- coding: utf-8 -*-
"""Varithon_FaceRecognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzMP-Nq-ftgjqI61OMrSWUVciAOCxDkr
"""

!pip install insightface opencv-python-headless scikit-learn matplotlib
!pip install -q onnxruntime-gpu
!pip install -q kagglehub

import kagglehub
kaggle_path = kagglehub.dataset_download("jessicali9530/lfw-dataset")
print(kaggle_path)

!python calibrate_face_threshold.py --source kaggle --kaggle_path "{kaggle_path}"